################################################################################
# Amateur Radio Services
################################################################################
# docker-compose -f docker-compose.yml -p amateur-radio-services up
# Requires environment for the QRZ credentials and aprs.fi api
################################################################################
services:
  amateur-radio-services:
    image: ghcr.io/jeffu231/amateurradioservices:latest
    container_name: amateur-radio-api
    restart: unless-stopped
    networks:
      - traefik-net
    environment:
      - QrzUsername=${QrzUsername}
      - QrzPassword=${QrzPassword}
      - AprsApiKey=${AprsApiKey}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amateur-radio-utilities-api.rule=Host(`$HOSTNAME`) && (PathPrefix(`/api/ars/`))"

networks:
  traefik-net:
    external: true
   
